#!/bin/sh

export GEM_PATH="$(hab pkg path core/dcob)/bundle/ruby/2.3.0:$(hab pkg path core/ruby)/lib/ruby/gems/2.3.0"

cd /hab/svc/dcob

if [ "$(whoami)" = "root" ]; then
  exec chpst \
    -U hab:hab \
    -u hab:hab \
    dcob -o 0.0.0.0 2>&1
else
  exec dcob -o 0.0.0.0 2>&1
fi
