# frozen_string_literal: true
require "bundler/gem_tasks"
require "rspec/core/rake_task"
require "chefstyle"
require "rubocop/rake_task"

RuboCop::RakeTask.new do |task|
  task.options << "--display-cop-names"
end

RSpec::Core::RakeTask.new(:spec)

task :test do
  Rake::Task["spec"].invoke
  Rake::Task["rubocop"].invoke
end

task default: :test
